set identity_insert [Character] on

--//																																								  Str,Mag,Skl,Spd,Lck,Def,Res
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (1, 'Avatar (M)', 'Male',		0,	0,	0,	0,	0,	0,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (2, 'Avatar (F)', 'Female',		0,	0,	0,	0,	0,	0,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (3, 'Chrom', 'Male',				1,	0,	1,	1,	1, -1, -1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (4, 'Lissa', 'Female',			-2,	2, -1,	1,	1, -1, -1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (5, 'Frederick', 'Male',			2, -2,	2, -2,	0,	2,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (6, 'Sully', 'Female',			-1,	-1,	2,	2,	0,	-1,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (7, 'Virion', 'Male',			0,	0,	2,	2,	-1,	-2,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (8, 'Stahl', 'Male',				2,	-1,	1,	0,	-2,	2,	-1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (9, 'Vaike', 'Male',				3,	-2,	1,	1,	-1,	0,	-2	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (10, 'Miriel', 'Female',			-2,	3,	1,	1,	0,	-2,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (11, 'Sumia', 'Female',			-2,	0,	2,	3,	0,	-2,	1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (12, 'Kellam', 'Male',			1,	0,	1,	-2,	-2,	3,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (13, 'Donnel', 'Male',			1,	-1,	-1,	-1,	3,	1,	-1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (14, 'Lon''qu', 'Male',			0,	0,	3,	3,	0,	-2,	-2	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (15, 'Ricken', 'Male',			-1,	2,	0,	0,	1,	-1,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (16, 'Maribelle', 'Female',		-3,	2,	1,	0,	3,	-3,	2	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (17, 'Panne', 'Female',			2,	-1,	2,	3,	-1,	1,	-1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (18, 'Gaius', 'Male',			1,	-1,	2,	2,	-2,	-1,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (19, 'Cordelia', 'Female',		1,	-1,	2,	2,	-1,	0,	-1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (20, 'Gregor', 'Male',			2,	-1,	2,	0,	-1,	1,	-2	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (21, 'Nowi', 'Female',			1,	1,	-1,	-2,	1,	3,	2	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (22, 'Libra', 'Male',			0,	1,	1,	0,	-1,	0,	1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (23, 'Tharja', 'Female',			0,	3,	-1,	1,	-3,	1,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (24, 'Anna', 'Female',			-1,	0,	1,	0,	3,	-1,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (25, 'Olivia', 'Female',			0,	0,	1,	1,	0,	-1,	-1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (26, 'Cherche', 'Female',		3,	0,	-1,	-1,	0,	0,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (27, 'Henry', 'Male',			1,	1,	2,	0,	-2,	1,	-1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (28, 'Say''ri', 'Female',		1,	-1,	1,	1,	-1,	0,	1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (29, 'Tiki', 'Female',			0,	-1,	0,	1,	2,	1,	2	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (30, 'Basilio', 'Male',			3,	-2,	1,	1,	-1,	1,	-1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (31, 'Flavia', 'Female',			1,	-1,	1,	1,	0,	-1,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (32, 'Gangrel', 'Male',			-2,	0,	3,	3,	-1,	-1,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (33, 'Walhart', 'Male',			4,	-2,	0,	-1,	-1,	4,	-2	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (34, 'Emmeryn', 'Female',		-2,	4,	0,	1,	0,	-2,	-1	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (35, 'Yen''fay', 'Male',			1,	-2,	2,	4,	0,	-1,	-2	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (36, 'Aversa', 'Female',			-1,	3,	1,	1,	-2,	0,	0	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (37, 'Priam', 'Male',			3,	-2,	1,	0,	0,	2,	-2	, NULL)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (38, 'Morgan (M)', 'Male',		1,	1,	1,	1,	1,	1,	1, 2)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (39, 'Morgan (F)', 'Female',		1,	1,	1,	1,	1,	1,	1, 1)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (40, 'Lucina', 'Female',			1,	1,	1,	1,	1,	1,	1, 3)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (41, 'Owain', 'Male',			1,	1,	1,	1,	1,	1,	1, 4)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (42, 'Inigo', 'Male',			1,	1,	1,	1,	1,	1,	1, 25)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (43, 'Brady', 'Male',			1,	1,	1,	1,	1,	1,	1, 16)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (44, 'Kjelle', 'Female',			1,	1,	1,	1,	1,	1,	1, 6)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (45, 'Cynthia', 'Female',		1,	1,	1,	1,	1,	1,	1, 11)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (46, 'Severa', 'Female',			1,	1,	1,	1,	1,	1,	1, 19)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (47, 'Gerome', 'Male',			1,	1,	1,	1,	1,	1,	1, 26)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (48, 'Yarne', 'Male',			1,	1,	1,	1,	1,	1,	1, 17)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (49, 'Laurent', 'Male',			1,	1,	1,	1,	1,	1,	1, 10)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (50, 'Noire', 'Female',			1,	1,	1,	1,	1,	1,	1, 23)
insert into [Character] ([CharacterID], [Name], [Gender], [ModStr], [ModMag], [ModSkl], [ModSpd], [ModLck], [ModDef], [ModRes], [ParentID]) values (51, 'Nah', 'Female',			1,	1,	1,	1,	1,	1,	1, 21)

set identity_insert [Character] off

