//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEAModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public Character()
        {
            this.Children = new HashSet<Character>();
            this.Characters1 = new HashSet<Character>();
            this.Characters = new HashSet<Character>();
            this.Classes = new HashSet<Class>();
        }
    
        public long CharacterID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public int ModStr { get; set; }
        public int ModMag { get; set; }
        public int ModSkl { get; set; }
        public int ModSpd { get; set; }
        public int ModLck { get; set; }
        public int ModDef { get; set; }
        public int ModRes { get; set; }
        public Nullable<long> ParentID { get; set; }
    
        public virtual ICollection<Character> Children { get; set; }
        public virtual Character Parent { get; set; }
        public virtual ICollection<Character> Characters1 { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
    }
}
