//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEAModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public Character()
        {
            this.ClassSets = new HashSet<ClassSet>();
            this.Supports = new HashSet<Support>();
            this.Supports1 = new HashSet<Support>();
        }
    
        public long CharacterID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public int ModStr { get; set; }
        public int ModMag { get; set; }
        public int ModSkl { get; set; }
        public int ModSpd { get; set; }
        public int ModLck { get; set; }
        public int ModDef { get; set; }
        public int ModRes { get; set; }
    
        public virtual ICollection<ClassSet> ClassSets { get; set; }
        public virtual ICollection<Support> Supports { get; set; }
        public virtual ICollection<Support> Supports1 { get; set; }
    }
}
