//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEAModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.PromotedClasses = new HashSet<Class>();
            this.BaseClasses = new HashSet<Class>();
            this.Characters = new HashSet<Character>();
        }
    
        public int ClassID { get; set; }
        public string Name { get; set; }
        public int MaxHP { get; set; }
        public int MaxStr { get; set; }
        public int MaxMag { get; set; }
        public int MaxSkl { get; set; }
        public int MaxSpd { get; set; }
        public int MaxLck { get; set; }
        public int MaxDef { get; set; }
        public int MaxRes { get; set; }
        public bool IsBaseClass { get; set; }
    
        public virtual ICollection<Class> PromotedClasses { get; set; }
        public virtual ICollection<Class> BaseClasses { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
    }
}
