//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEAModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassPromotion
    {
        public int ID { get; set; }
        public int BaseClassID { get; set; }
        public int PromotedClassID { get; set; }
    
        public virtual Class BaseClass { get; set; }
        public virtual Class PromotedClass { get; set; }
    }
}
