//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEAModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int ID { get; set; }
        public long CharacterID { get; set; }
        public long SupportID { get; set; }
        public string SupportRank { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Character Character1 { get; set; }
    }
}
